# Generated by Django 5.2.8 on 2026-05-04 01:13

import cloudinary_storage.storage
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Nombre del Servicio')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='servicios/')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='servicios/imagenes_extra/')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_extra', to='core.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudInformacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener el formato 569XXXXXXXX', regex='^569\\d{8}$')])),
                ('tienes_terreno', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=10)),
                ('ubicacion', models.CharField(max_length=255)),
                ('cuando_comenzar', models.CharField(max_length=20)),
                ('requerimientos', models.TextField()),
                ('estado', models.CharField(choices=[('no_revisada', 'No revisada'), ('revisada', 'Revisada por experto'), ('asignada', 'Experto asignado'), ('cotizada', 'Cotización generada'), ('enviada', 'Cotización enviada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('pagada', 'Pagada')], default='no_revisada', max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('codigo_seguimiento', models.CharField(blank=True, max_length=30, unique=True)),
                ('comentarios_cambios', models.TextField(blank=True, null=True)),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='core.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='presupuestos/')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto', to='core.solicitudinformacion')),
            ],
        ),
    ]
