# Generated by Django 5.2.8 on 2026-05-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenservicio',
            name='imagen',
            field=models.ImageField(upload_to='servicios/imagenes_extra/'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='archivo',
            field=models.FileField(upload_to='presupuestos/'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(upload_to='servicios/imagenes_extra/'),
        ),
    ]
