# Generated by Django 5.2.8 on 2026-06-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_imagenservicio_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudinformacion',
            name='progreso_trabajo',
            field=models.IntegerField(default=0, help_text='Porcentaje de progreso (0-100)'),
        ),
        migrations.AlterField(
            model_name='solicitudinformacion',
            name='estado',
            field=models.CharField(choices=[('no_revisada', 'No revisada'), ('revisada', 'Revisada por experto'), ('asignada', 'Experto asignado'), ('cotizada', 'Cotización generada'), ('enviada', 'Cotización enviada'), ('aceptada', 'Aceptada'), ('pago_inicial', 'Pago 50% Inicial'), ('en_ejecucion', 'En Ejecución'), ('rechazada', 'Rechazada'), ('pagada', 'Pagada')], default='no_revisada', max_length=20),
        ),
    ]
