# Generated by Django 5.2.8 on 2026-06-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_solicitudinformacion_progreso_trabajo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudinformacion',
            name='fecha_estimado_finalizacion',
            field=models.DateField(blank=True, help_text='Fecha estimada de finalización del proyecto', null=True),
        ),
    ]
