# Generated by Django 5.2.8 on 2026-06-08 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_solicitudinformacion_fecha_estimado_finalizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudinformacion',
            name='estado',
            field=models.CharField(choices=[('no_revisada', 'No revisada'), ('revisada', 'Revisada por experto'), ('asignada', 'Experto asignado'), ('cotizada', 'Cotización generada'), ('enviada', 'Cotización enviada'), ('aceptada', 'Aceptada'), ('pago_inicial', 'Pago 50% Inicial'), ('en_ejecucion', 'En Ejecución'), ('completado', 'Completado'), ('pagada', 'Pagada'), ('rechazada', 'Rechazada')], default='no_revisada', max_length=20),
        ),
        migrations.CreateModel(
            name='Modificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('monto_adicional', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('admin_monto_propuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('aceptada', models.BooleanField(default=False)),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True)),
                ('admin_observaciones', models.TextField(blank=True, null=True)),
                ('presupuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modificaciones', to='core.presupuesto')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modificaciones', to='core.solicitudinformacion')),
            ],
        ),
    ]
