# Generated by Django 5.2.8 on 2026-06-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_solicitudinformacion_estado_modificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='modificacion',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='modificaciones/'),
        ),
        migrations.AddField(
            model_name='modificacion',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modificacion',
            name='urgencia',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10),
        ),
    ]
