# Generated by Django 5.2.8 on 2026-06-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_modificacion_adjunto_modificacion_fecha_limite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modificacion',
            name='codigo_seguimiento_cliente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='modificacion',
            name='contacto_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='modificacion',
            name='contacto_nombre',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='modificacion',
            name='especificaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modificacion',
            name='motivo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
