# Generated by Django 5.2.8 on 2026-06-08 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_modificacion_codigo_seguimiento_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modificacion',
            name='fecha_limite',
        ),
        migrations.RemoveField(
            model_name='modificacion',
            name='urgencia',
        ),
    ]
