# Generated by Django 5.2.8 on 2026-06-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_modificacion_fecha_limite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modificacion',
            name='estado_mod',
            field=models.CharField(choices=[('creada', 'Creada'), ('en_revision', 'En revisión'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='creada', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudinformacion',
            name='estado',
            field=models.CharField(choices=[('no_revisada', 'No revisada'), ('revisada', 'Revisada por experto'), ('asignada', 'Experto asignado'), ('cotizada', 'Cotización generada'), ('enviada', 'Cotización enviada'), ('aceptada', 'Aceptada'), ('mod_creada', 'Modificación: Creada'), ('mod_en_revision', 'Modificación: En revisión'), ('mod_aceptada', 'Modificación: Aceptada'), ('mod_rechazada', 'Modificación: Rechazada'), ('pago_inicial', 'Pago 50% Inicial'), ('en_ejecucion', 'En Ejecución'), ('completado', 'Completado'), ('pagada', 'Pagada'), ('rechazada', 'Rechazada')], default='no_revisada', max_length=20),
        ),
    ]
