# Generated by Django 5.2.8 on 2026-06-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_modificacion_estado_mod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('rut', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=12)),
                ('fecha_inicio_preferido', models.DateField()),
                ('fecha_fin_preferido', models.DateField()),
                ('fecha_inicio_propuesta', models.DateField(blank=True, null=True)),
                ('fecha_fin_propuesta', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('propuesta', 'Propuesta de nueva fecha'), ('confirmada', 'Confirmada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
