# Generated by Django 5.2.8 on 2026-06-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_visita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('orden', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('template', models.CharField(max_length=100)),
            ],
        ),
    ]
