# Generated by Django 5.2.8 on 2026-06-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='visitas/evidencias/'),
        ),
    ]