# Generated by Django 5.2.8 on 2026-06-30 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudinformacion',
            name='estado',
        ),
        migrations.AddField(
            model_name='solicitudinformacion',
            name='estado_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='core.estado'),
        ),
    ]
