# Generated by Django 5.2.8 on 2026-06-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_visita_evidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='evidencia_observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]