# Generated by Django 5.2.8 on 2026-06-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_solicitudinformacion_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudinformacion',
            name='fecha_estimado_finalizacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
