# Generated by Django 5.2.8 on 2026-06-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_solicitudinformacion_fecha_estimado_finalizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudinformacion',
            name='progreso_trabajo',
            field=models.IntegerField(default=0),
        ),
    ]
