# Generated by Django 5.2.8 on 2026-06-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_visita_evidencia_observaciones'),
        ('core', '0014_alter_solicitudinformacion_progreso_trabajo'),
    ]

    operations = [
    ]
