# Generated by Django 5.2.8 on 2026-06-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20260630_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='presupuestos/'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Solicitud creada'), ('propuesta', 'En revisión'), ('confirmada', 'Aceptada'), ('rechazada', 'Solicitud rechazada')], default='pendiente', max_length=20),
        ),
    ]
